import { OFFICE_CATALOG } from '../constants';
import { DomainInvariantError } from './errors';
import { assertScopePattern } from './scopeMatch';

/** Native employee position catalog, re-engineered from the committed Agency Agents
 * workforce blueprint (imports/agency-agents/agency-agents-workforce-map.json, MIT -
 * see ATTRIBUTION.md). Eighty positions: four offices, twenty departments, exactly
 * four employees per department, matching the EMPLOYEE_SLOTS invariant. Capabilities
 * are the kebab labels routed through task requiredCapabilities and matched against
 * assignee.capabilities; shared skills resolve separately by skill:<name> slugs.
 *
 * readScope/writeScope/commandScope record what the position DECLares it needs
 * (blueprint templates). They are never grants: task-time permissions come only from
 * the task's persisted manifest enforced by TaskScopedTools, and the audit helper in
 * src/application/positionManifestAudit.js flags manifests exceeding this declared
 * scope. toolRequirements are descriptive planning metadata only. */

const POSITION_DEFS = [
    Object.freeze({ office: "game-development", department: "game-engine-systems", slot: 1, name: "Unreal Systems Engineer", position: "Senior Unreal Engine Systems Specialist", capabilities: Object.freeze(["gameplay-systems", "ability-system", "unreal-architecture", "actor-lifecycle"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:unreal-cli", "process:execute:cmake"]), readScope: Object.freeze(["Source/**", "Config/**", "*.uproject"]), writeScope: Object.freeze(["Source/**", "Config/**"]), commandScope: Object.freeze(["dotnet", "build", "msbuild"]), verification: "Compile check with Unreal Build Tool; unit tests in Unreal Test Automation harness.", provenance: "imports/agency-agents/game-development/unreal-engine/unreal-systems-engineer.md" }),
    Object.freeze({ office: "game-development", department: "game-engine-systems", slot: 2, name: "Unity Systems Architect", position: "Senior Unity Data-Driven Systems Architect", capabilities: Object.freeze(["unity-systems", "scriptable-objects", "component-refactoring", "editor-tools"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:dotnet"]), readScope: Object.freeze(["Assets/**", "Packages/**", "ProjectSettings/**"]), writeScope: Object.freeze(["Assets/**", "ProjectSettings/**"]), commandScope: Object.freeze(["dotnet", "unity-cmd"]), verification: "Unity Test Runner batch execution; zero missing reference checks; assembly definition validation.", provenance: "imports/agency-agents/game-development/unity/unity-architect.md" }),
    Object.freeze({ office: "game-development", department: "game-engine-systems", slot: 3, name: "Godot & Multiplatform Gameplay Scripter", position: "Godot & Multiplatform Gameplay Specialist", capabilities: Object.freeze(["godot-gameplay", "roblox-scripting", "node-architecture", "scene-tree"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:godot-cli"]), readScope: Object.freeze(["scenes/**", "scripts/**", "project.godot", "*.rbxl"]), writeScope: Object.freeze(["scenes/**", "scripts/**"]), commandScope: Object.freeze(["godot", "rojo"]), verification: "Godot headless GUT test execution; Luau type check and linter.", provenance: "imports/agency-agents/game-development/godot/godot-gameplay-scripter.md" }),
    Object.freeze({ office: "game-development", department: "game-engine-systems", slot: 4, name: "Multiplayer Network Engineer", position: "Game Networking & Multiplayer Architect", capabilities: Object.freeze(["network-replication", "multiplayer-sync", "tick-simulation", "bandwidth-optimization"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:network-test"]), readScope: Object.freeze(["Source/**", "Assets/**", "scripts/**"]), writeScope: Object.freeze(["Source/**", "Assets/**", "scripts/**"]), commandScope: Object.freeze(["dotnet", "pytest"]), verification: "Multi-client loopback tests, latency simulation verification, packet inspection logs.", provenance: "imports/agency-agents/game-development/unreal-engine/unreal-multiplayer-architect.md" }),
    Object.freeze({ office: "game-development", department: "game-design-creative", slot: 1, name: "Core Mechanics & Experience Designer", position: "Lead Gameplay Mechanics & Experience Designer", capabilities: Object.freeze(["gdd-creation", "mechanics-design", "onboarding-flow", "gameplay-tuning"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/design/**", "Configs/**", "Data/**"]), writeScope: Object.freeze(["docs/design/**", "Configs/**", "Data/**"]), commandScope: Object.freeze([]), verification: "Design spec review, configuration table consistency, mathematical balance checks.", provenance: "imports/agency-agents/game-development/game-designer.md" }),
    Object.freeze({ office: "game-development", department: "game-design-creative", slot: 2, name: "Level & World Designer", position: "Level Architecture & World Building Specialist", capabilities: Object.freeze(["level-blockout", "world-partitioning", "pacing-layout", "pcg-rules"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["Content/Maps/**", "Assets/Scenes/**", "docs/levels/**"]), writeScope: Object.freeze(["Content/Maps/**", "Assets/Scenes/**", "docs/levels/**"]), commandScope: Object.freeze([]), verification: "Map collision checks, streaming partition bounds validation, traversal timing tests.", provenance: "imports/agency-agents/game-development/level-designer.md" }),
    Object.freeze({ office: "game-development", department: "game-design-creative", slot: 3, name: "Game Economy & Progression Balancer", position: "In-Game Economy & Progression Balancer", capabilities: Object.freeze(["economy-balancing", "progression-curves", "loot-tables", "drop-rates"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["Data/Economy/**", "Data/Progression/**"]), writeScope: Object.freeze(["Data/Economy/**", "Data/Progression/**"]), commandScope: Object.freeze(["node"]), verification: "Monte Carlo simulation runs (10,000 player journeys); inflation threshold checks.", provenance: "imports/agency-agents/game-development/economy-designer.md" }),
    Object.freeze({ office: "game-development", department: "game-design-creative", slot: 4, name: "Narrative & Quest Designer", position: "Narrative Systems & Branching Dialogue Designer", capabilities: Object.freeze(["dialogue-trees", "quest-design", "narrative-scripting", "lore-spec"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["Data/Dialogues/**", "Data/Quests/**", "docs/narrative/**"]), writeScope: Object.freeze(["Data/Dialogues/**", "Data/Quests/**", "docs/narrative/**"]), commandScope: Object.freeze([]), verification: "Dialogue acyclic graph validation, dead-end state checks, quest condition unit tests.", provenance: "imports/agency-agents/game-development/narrative-designer.md" }),
    Object.freeze({ office: "game-development", department: "tech-art-audio", slot: 1, name: "Real-Time Technical Artist", position: "DCC-to-Engine Technical Artist & Asset Automator", capabilities: Object.freeze(["asset-pipeline", "blender-automation", "rigging-validation", "lod-optimization"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:blender"]), readScope: Object.freeze(["Art/**", "Assets/Models/**", "scripts/blender/**"]), writeScope: Object.freeze(["Assets/Models/**", "scripts/blender/**"]), commandScope: Object.freeze(["blender", "python"]), verification: "Asset polycount/bone count automated audit; vertex normal and UV validation scripts.", provenance: "imports/agency-agents/game-development/technical-artist.md" }),
    Object.freeze({ office: "game-development", department: "tech-art-audio", slot: 2, name: "Shader & Graphics Developer", position: "Real-Time Shader & GPU Performance Engineer", capabilities: Object.freeze(["shader-creation", "vfx-pipeline", "gpu-profiling", "render-feature"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["Shaders/**", "Materials/**", "VFX/**"]), writeScope: Object.freeze(["Shaders/**", "Materials/**", "VFX/**"]), commandScope: Object.freeze([]), verification: "Shader compilation check on target graphics APIs; instruction count and texture sample benchmarks.", provenance: "imports/agency-agents/game-development/unity/unity-shader-graph-artist.md" }),
    Object.freeze({ office: "game-development", department: "tech-art-audio", slot: 3, name: "Spatial & XR Interaction Developer", position: "Immersive VR/AR & Spatial Interface Engineer", capabilities: Object.freeze(["xr-interactions", "spatial-ui", "hand-tracking", "vr-comfort"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["XR/**", "SpatialUI/**"]), writeScope: Object.freeze(["XR/**", "SpatialUI/**"]), commandScope: Object.freeze([]), verification: "Simulated 6DoF interaction unit tests; frame rate stability audit (target 90/120 Hz).", provenance: "imports/agency-agents/spatial-computing/xr-immersive-developer.md" }),
    Object.freeze({ office: "game-development", department: "tech-art-audio", slot: 4, name: "Game Audio & Acoustic Engineer", position: "Dynamic Game Audio & Soundscapes Engineer", capabilities: Object.freeze(["audio-implementation", "soundbank-setup", "spatial-acoustics", "voice-pipeline"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["Audio/**", "Content/Audio/**", "Assets/Audio/**"]), writeScope: Object.freeze(["Audio/**", "Content/Audio/**", "Assets/Audio/**"]), commandScope: Object.freeze([]), verification: "Audio bank build verification; voice concurrency and memory footprint budget audit.", provenance: "imports/agency-agents/game-development/game-audio-engineer.md" }),
    Object.freeze({ office: "game-development", department: "game-production-qa", slot: 1, name: "Studio Production Coordinator", position: "Game Studio Delivery & Pipeline Coordinator", capabilities: Object.freeze(["production-scheduling", "dependency-tracking", "milestone-coordination"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/production/**", "milestones/**"]), writeScope: Object.freeze(["docs/production/**", "milestones/**"]), commandScope: Object.freeze([]), verification: "Dependency graph cycle detection; delivery checklist signoff verification.", provenance: "imports/agency-agents/project-management/project-management-studio-producer.md" }),
    Object.freeze({ office: "game-development", department: "game-production-qa", slot: 2, name: "Game Performance & Profiling Engineer", position: "Frame-Time & Runtime Memory Optimization Engineer", capabilities: Object.freeze(["frame-profiling", "memory-budget-audit", "draw-call-optimization", "bottleneck-analysis"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:profiler"]), readScope: Object.freeze(["Source/**", "Assets/**", "benchmarks/**"]), writeScope: Object.freeze(["benchmarks/**"]), commandScope: Object.freeze(["node", "pytest"]), verification: "Automated benchmark runs with frame time percentiles (<16.6ms for 60fps; <11.1ms for 90fps).", provenance: "imports/agency-agents/engineering/engineering-autonomous-optimization-architect.md" }),
    Object.freeze({ office: "game-development", department: "game-production-qa", slot: 3, name: "Game QA & Automated Playtester", position: "Automated Gameplay Test & Regression Specialist", capabilities: Object.freeze(["automated-playtest", "input-replay", "regression-test", "save-state-fuzzing"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:game-test"]), readScope: Object.freeze(["tests/**", "Assets/Tests/**", "Source/**"]), writeScope: Object.freeze(["tests/**", "test-results/**"]), commandScope: Object.freeze(["node", "pytest", "dotnet"]), verification: "Zero crash exits on 100-loop smoke pass; complete test evidence bundle capture.", provenance: "imports/agency-agents/testing/testing-test-automation-engineer.md" }),
    Object.freeze({ office: "game-development", department: "game-production-qa", slot: 4, name: "Game Build & Distribution Engineer", position: "Game Build Pipeline & Platform Packaging Specialist", capabilities: Object.freeze(["game-packaging", "asset-cooking", "symbol-archiving", "release-build"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:build-engine"]), readScope: Object.freeze(["Source/**", "Assets/**", "Config/**", "build/**"]), writeScope: Object.freeze(["build/**", "dist/**"]), commandScope: Object.freeze(["dotnet", "msbuild", "tar", "zip"]), verification: "VSIX / game package binary verification; checksum manifest generation; clean test install.", provenance: "imports/agency-agents/engineering/engineering-developer-tooling-engineer.md" }),
    Object.freeze({ office: "website-development", department: "frontend", slot: 1, name: "Web UI Application Engineer", position: "Senior Web Application & UI Component Engineer", capabilities: Object.freeze(["ui-components", "state-management", "responsive-layout", "client-logic"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:npm"]), readScope: Object.freeze(["src/**", "public/**", "package.json"]), writeScope: Object.freeze(["src/**", "public/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "Component render unit tests; zero layout overflow in narrow/wide viewports.", provenance: "imports/agency-agents/engineering/engineering-frontend-developer.md" }),
    Object.freeze({ office: "website-development", department: "frontend", slot: 2, name: "Frontend Architecture & Wasm Engineer", position: "Frontend Platform & High-Performance Compute Specialist", capabilities: Object.freeze(["frontend-build", "wasm-integration", "bundle-optimization", "worker-threads"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:esbuild"]), readScope: Object.freeze(["src/**", "esbuild.js", "package.json"]), writeScope: Object.freeze(["src/**", "out/**", "esbuild.js"]), commandScope: Object.freeze(["node", "npm"]), verification: "Bundle size metafile analysis; Wasm module memory safety and benchmark checks.", provenance: "imports/agency-agents/engineering/engineering-webassembly-engineer.md" }),
    Object.freeze({ office: "website-development", department: "frontend", slot: 3, name: "Accessibility & WCAG Specialist", position: "Web Accessibility (A11y) & Section 508 Specialist", capabilities: Object.freeze(["a11y-audit", "aria-semantics", "keyboard-navigation", "contrast-check"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:axe"]), readScope: Object.freeze(["src/**", "tests/**"]), writeScope: Object.freeze(["src/**", "tests/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Zero axe-core automated violations; keyboard traversal test pass without mouse traps.", provenance: "imports/agency-agents/engineering/engineering-section-508-specialist.md" }),
    Object.freeze({ office: "website-development", department: "frontend", slot: 4, name: "Internationalization & Localization Engineer", position: "Frontend i18n & Localization Specialist", capabilities: Object.freeze(["i18n-extraction", "rtl-layout", "locale-formatting", "string-bundling"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "package.nls.json", "locales/**"]), writeScope: Object.freeze(["src/**", "package.nls.json", "locales/**"]), commandScope: Object.freeze([]), verification: "Pseudo-localization test pass; missing key linting; RTL mirroring layout validation.", provenance: "imports/agency-agents/engineering/engineering-i18n-engineer.md" }),
    Object.freeze({ office: "website-development", department: "backend", slot: 1, name: "Backend Systems Architect", position: "Senior Modular Backend Architect", capabilities: Object.freeze(["domain-logic", "use-cases", "architecture-scaffolding", "backend-refactoring"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/domain/**", "src/application/**", "src/infrastructure/**"]), writeScope: Object.freeze(["src/domain/**", "src/application/**", "src/infrastructure/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Domain invariant unit tests; dependency rule boundary checks (no outer-layer leakage).", provenance: "imports/agency-agents/engineering/engineering-backend-architect.md" }),
    Object.freeze({ office: "website-development", department: "backend", slot: 2, name: "API Platform & Contract Engineer", position: "API Gateway & Contract Integration Engineer", capabilities: Object.freeze(["api-contract", "schema-validation", "endpoint-versioning", "rate-limiting"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:api-validator"]), readScope: Object.freeze(["src/api/**", "docs/api/**", "schemas/**"]), writeScope: Object.freeze(["src/api/**", "docs/api/**", "schemas/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Contract validation tests (e.g. Prism/Supertest); schema regression checks against previous versions.", provenance: "imports/agency-agents/engineering/engineering-api-platform-engineer.md" }),
    Object.freeze({ office: "website-development", department: "backend", slot: 3, name: "Real-Time & Event Stream Engineer", position: "Real-Time Collaboration & Event Message Engineer", capabilities: Object.freeze(["websocket-handling", "event-streaming", "presence-sync", "message-ordering"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/infrastructure/**", "src/application/**"]), writeScope: Object.freeze(["src/infrastructure/**", "src/application/**"]), commandScope: Object.freeze(["node"]), verification: "Concurrent connection stress test; message ordering and delivery guarantee tests.", provenance: "imports/agency-agents/engineering/engineering-realtime-collaboration-engineer.md" }),
    Object.freeze({ office: "website-development", department: "backend", slot: 4, name: "Integration & Payments Engineer", position: "External Services & Billing Integration Specialist", capabilities: Object.freeze(["webhook-handling", "payment-integration", "billing-lifecycle", "external-adapter"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/integrations/**", "src/infrastructure/**"]), writeScope: Object.freeze(["src/integrations/**", "src/infrastructure/**"]), commandScope: Object.freeze(["node"]), verification: "Simulated webhook replay tests; idempotency duplicate submission rejection tests.", provenance: "imports/agency-agents/engineering/engineering-payments-billing-engineer.md" }),
    Object.freeze({ office: "website-development", department: "ui-ux", slot: 1, name: "Product UI Designer", position: "Senior UI & Design Systems Specialist", capabilities: Object.freeze(["design-system", "ui-styling", "theme-tokens", "visual-hierarchy"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["media/**", "src/ui/**", "styles/**"]), writeScope: Object.freeze(["media/**", "src/ui/**", "styles/**"]), commandScope: Object.freeze([]), verification: "Visual regression snapshots; design token contrast and theme switching verification.", provenance: "imports/agency-agents/design/design-ui-designer.md" }),
    Object.freeze({ office: "website-development", department: "ui-ux", slot: 2, name: "Information & Interaction Architect", position: "Information Architecture & UX Interaction Architect", capabilities: Object.freeze(["ia-mapping", "interaction-wireframes", "workflow-ergonomics", "modal-logic"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/ux/**", "src/ui/**"]), writeScope: Object.freeze(["docs/ux/**", "src/ui/**"]), commandScope: Object.freeze([]), verification: "Task click-depth audits (<3 clicks for critical paths); cognitive walkthrough rubric evaluation.", provenance: "imports/agency-agents/design/design-ux-architect.md" }),
    Object.freeze({ office: "website-development", department: "ui-ux", slot: 3, name: "UX Researcher & Usability Analyst", position: "UX Research & Usability Feedback Analyst", capabilities: Object.freeze(["usability-audit", "persona-walkthrough", "friction-analysis", "feedback-synthesis"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/research/**", "docs/feedback/**"]), writeScope: Object.freeze(["docs/research/**", "docs/feedback/**"]), commandScope: Object.freeze([]), verification: "Heuristic evaluation scorecard; usability gap recommendations mapped to engineering tasks.", provenance: "imports/agency-agents/design/design-ux-researcher.md" }),
    Object.freeze({ office: "website-development", department: "ui-ux", slot: 4, name: "UI Finish & Visual Quality Reviewer", position: "UI Polish & Visual Quality Gate Reviewer", capabilities: Object.freeze(["visual-quality-gate", "ui-polish-review", "truncation-check", "focus-outline-audit"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "media/**", "styles/**"]), writeScope: Object.freeze(["src/**", "styles/**"]), commandScope: Object.freeze([]), verification: "UI gate checklist signoff; zero horizontal overflow in narrow panels (Phase 440 adherence).", provenance: "imports/agency-agents/design/design-ui-finish-gate-reviewer.md" }),
    Object.freeze({ office: "website-development", department: "qa-testing", slot: 1, name: "Test Automation Lead", position: "Senior Test Automation & E2E Harness Architect", capabilities: Object.freeze(["test-suite-creation", "integration-tests", "fixture-setup", "mock-providers"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:vitest"]), readScope: Object.freeze(["tests/**", "src/**", "package.json"]), writeScope: Object.freeze(["tests/**", "test/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "Full test suite execution pass with zero skips/errors; deterministic runtime under 60 seconds.", provenance: "imports/agency-agents/testing/testing-test-automation-engineer.md" }),
    Object.freeze({ office: "website-development", department: "qa-testing", slot: 2, name: "API & Contract Testing Specialist", position: "API Regression & Contract Testing Specialist", capabilities: Object.freeze(["api-testing", "contract-verification", "fuzz-testing", "boundary-testing"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:npm"]), readScope: Object.freeze(["tests/api/**", "src/api/**"]), writeScope: Object.freeze(["tests/api/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "100% endpoint status code coverage; invalid payload 4xx rejection verification.", provenance: "imports/agency-agents/testing/testing-api-tester.md" }),
    Object.freeze({ office: "website-development", department: "qa-testing", slot: 3, name: "Failure Diagnostics & Flake Analyst", position: "Test Diagnostics & Flaky Test Elimination Specialist", capabilities: Object.freeze(["flake-triaging", "failure-analysis", "race-condition-fix", "test-stabilization"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["tests/**", "src/**", "*.log"]), writeScope: Object.freeze(["tests/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "Flake-free pass over 50 consecutive test runs in parallel execution mode.", provenance: "imports/agency-agents/testing/testing-test-results-analyzer.md" }),
    Object.freeze({ office: "website-development", department: "qa-testing", slot: 4, name: "Evidence & Reality Verification Specialist", position: "Task Result Evidence & Reality Verification Specialist", capabilities: Object.freeze(["evidence-bundling", "reality-verification", "artifact-hashing", "result-proof"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["tests/**", "src/**", "out/**"]), writeScope: Object.freeze(["test-results/**", "evidence/**"]), commandScope: Object.freeze([]), verification: "Immutable, non-AI verifiable evidence packets; SHA-256 match between claims and outputs.", provenance: "imports/agency-agents/testing/testing-evidence-collector.md" }),
    Object.freeze({ office: "website-development", department: "security", slot: 1, name: "Application Security (AppSec) Engineer", position: "Application Security & Vulnerability Remediation Engineer", capabilities: Object.freeze(["appsec-review", "injection-prevention", "path-traversal-defense", "sanitization"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "package.json"]), writeScope: Object.freeze(["src/**"]), commandScope: Object.freeze([]), verification: "Automated SAST scan pass; negative exploit test cases (injection payloads return rejected/denied).", provenance: "imports/agency-agents/security/security-appsec-engineer.md" }),
    Object.freeze({ office: "website-development", department: "security", slot: 2, name: "AI Code Security Auditor", position: "AI-Generated Code Security Auditor", capabilities: Object.freeze(["ai-code-audit", "phantom-package-check", "hallucination-defense", "ast-audit"]), toolRequirements: Object.freeze(["filesystem:read"]), readScope: Object.freeze(["src/**", "package.json", "package-lock.json"]), writeScope: Object.freeze([]), commandScope: Object.freeze([]), verification: "Audit report with zero unvetted third-party package imports and verified call boundaries.", provenance: "imports/agency-agents/security/security-ai-generated-code-auditor.md" }),
    Object.freeze({ office: "website-development", department: "security", slot: 3, name: "Secrets & Credential Protection Specialist", position: "Secret Storage & Credential Boundary Specialist", capabilities: Object.freeze(["secret-scan", "credential-adapter", "redaction-verification", "auth-vault"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "*.json", "*.md"]), writeScope: Object.freeze(["src/infrastructure/**", "src/shared/**"]), commandScope: Object.freeze([]), verification: "Zero hardcoded high-entropy tokens across codebase; SecretStorage integration tests pass.", provenance: "imports/agency-agents/security/security-secrets-credential-engineer.md" }),
    Object.freeze({ office: "website-development", department: "security", slot: 4, name: "Threat Modeling & Pen Testing Lead", position: "Threat Modeling & Security Boundary Validator", capabilities: Object.freeze(["threat-modeling", "boundary-validation", "privilege-escalation-test"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "docs/security/**"]), writeScope: Object.freeze(["docs/security/**", "tests/security/**"]), commandScope: Object.freeze(["node"]), verification: "Threat model document signoff; adversarial penetration test cases confirm boundary enforcement.", provenance: "imports/agency-agents/security/security-architect.md" }),
    Object.freeze({ office: "website-development", department: "devops", slot: 1, name: "CI/CD Pipeline Automator", position: "Continuous Integration & Deployment Specialist", capabilities: Object.freeze(["ci-pipeline", "matrix-builds", "action-optimization", "release-workflow"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze([".github/workflows/**", "package.json"]), writeScope: Object.freeze([".github/workflows/**", "package.json"]), commandScope: Object.freeze([]), verification: "Clean CI runs across Windows, Ubuntu, and macOS runners with zero step timeouts.", provenance: "imports/agency-agents/engineering/engineering-devops-automator.md" }),
    Object.freeze({ office: "website-development", department: "devops", slot: 2, name: "Git Workflow & Branch Governance Specialist", position: "Git Branching & Release Hygiene Specialist", capabilities: Object.freeze(["git-workflow", "changelog-automation", "branch-protection", "release-tagging"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:git"]), readScope: Object.freeze(["CHANGELOG.md", "package.json"]), writeScope: Object.freeze(["CHANGELOG.md", "package.json"]), commandScope: Object.freeze(["git"]), verification: "git diff --check returns 0; commit history conforms to conventional commit specification.", provenance: "imports/agency-agents/engineering/engineering-git-workflow-master.md" }),
    Object.freeze({ office: "website-development", department: "devops", slot: 3, name: "Site Reliability Engineer (SRE)", position: "Service Reliability & Telemetry Monitoring Specialist", capabilities: Object.freeze(["sre-runbooks", "health-probes", "telemetry-logging", "postmortem-analysis"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "docs/runbooks/**"]), writeScope: Object.freeze(["src/**", "docs/runbooks/**"]), commandScope: Object.freeze([]), verification: "Health probe endpoint test; incident runbook simulation walk-through passes without human intervention.", provenance: "imports/agency-agents/engineering/engineering-sre.md" }),
    Object.freeze({ office: "website-development", department: "devops", slot: 4, name: "Cloud & Infrastructure Platform Engineer", position: "Cloud Infrastructure & Containerization Specialist", capabilities: Object.freeze(["cloud-infra", "containerization", "iac-configuration", "security-groups"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["infra/**", "Dockerfile", "package.json"]), writeScope: Object.freeze(["infra/**", "Dockerfile"]), commandScope: Object.freeze([]), verification: "Container image build succeeds with non-root user execution; IaC syntax check passes.", provenance: "imports/agency-agents/engineering/engineering-platform-engineer.md" }),
    Object.freeze({ office: "website-development", department: "database", slot: 1, name: "Data Systems & Schema Engineer", position: "Relational Schema Modeling & Migration Specialist", capabilities: Object.freeze(["schema-migration", "table-modeling", "foreign-keys", "data-seeding"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/storage/**", "scripts/**"]), writeScope: Object.freeze(["src/storage/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Sequential migration execution passes from v1 to latest schema; migration rollback verified.", provenance: "imports/agency-agents/engineering/engineering-data-engineer.md" }),
    Object.freeze({ office: "website-development", department: "database", slot: 2, name: "Database Query Optimizer", position: "SQL Performance Tuning & Index Strategy Engineer", capabilities: Object.freeze(["query-optimization", "index-creation", "explain-query-plan", "wal-tuning"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:sqlite"]), readScope: Object.freeze(["src/storage/**", "benchmarks/**"]), writeScope: Object.freeze(["src/storage/**", "benchmarks/**"]), commandScope: Object.freeze(["node"]), verification: "Query plan confirms SEARCH TABLE USING INDEX for all high-frequency lookups (zero full table scans).", provenance: "imports/agency-agents/engineering/engineering-database-optimizer.md" }),
    Object.freeze({ office: "website-development", department: "database", slot: 3, name: "Database Reliability & Recovery Specialist", position: "Database Resilience, Backup & Integrity Specialist", capabilities: Object.freeze(["db-backup", "integrity-check", "crash-recovery", "vacuum-maintenance"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/storage/**", "scripts/check-sqlite.js"]), writeScope: Object.freeze(["src/storage/**", "scripts/check-sqlite.js"]), commandScope: Object.freeze(["node"]), verification: "npm run check:sqlite exits 0; backup snapshot restore restores 100% of persisted rows.", provenance: "imports/agency-agents/engineering/engineering-database-reliability-engineer.md" }),
    Object.freeze({ office: "website-development", department: "database", slot: 4, name: "Data Retrieval & Semantic Search Engineer", position: "Full-Text Search & Semantic Retrieval Specialist", capabilities: Object.freeze(["fts-indexing", "semantic-search", "bm25-tuning", "vector-retrieval"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/storage/**", "src/domain/memoryRetrieval.js"]), writeScope: Object.freeze(["src/storage/**", "src/domain/memoryRetrieval.js"]), commandScope: Object.freeze(["node"]), verification: "Search benchmark tests verify recall@10 and precision metrics; query latency <10ms for 100k records.", provenance: "imports/agency-agents/engineering/engineering-search-relevance-engineer.md" }),
    Object.freeze({ office: "website-development", department: "performance", slot: 1, name: "Autonomous Optimization Architect", position: "Autonomous Profiling & Bottleneck Optimization Architect", capabilities: Object.freeze(["cpu-profiling", "event-loop-tuning", "heap-analysis", "bottleneck-removal"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/**", "benchmarks/**"]), writeScope: Object.freeze(["src/**", "benchmarks/**"]), commandScope: Object.freeze(["node"]), verification: "Benchmark execution confirms >20% throughput improvement with zero degradation under load.", provenance: "imports/agency-agents/engineering/engineering-autonomous-optimization-architect.md" }),
    Object.freeze({ office: "website-development", department: "performance", slot: 2, name: "Performance Benchmarking Specialist", position: "Continuous Performance Benchmarking Specialist", capabilities: Object.freeze(["benchmark-authoring", "latency-testing", "throughput-stress", "regression-gate"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:npm"]), readScope: Object.freeze(["benchmarks/**", "src/**"]), writeScope: Object.freeze(["benchmarks/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "npm run benchmark execution passes within defined variance thresholds; no regression alerts.", provenance: "imports/agency-agents/testing/testing-performance-benchmarker.md" }),
    Object.freeze({ office: "website-development", department: "performance", slot: 3, name: "Minimal-Change Remediation Specialist", position: "Surgical Patching & Minimal-Diff Remediation Specialist", capabilities: Object.freeze(["surgical-bugfix", "minimal-diff-patch", "targeted-hotfix", "regression-avoidance"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "tests/**"]), writeScope: Object.freeze(["src/**", "tests/**"]), commandScope: Object.freeze([]), verification: "git diff --stat verifies fewest lines touched to resolve issue; 100% test pass on touched modules.", provenance: "imports/agency-agents/engineering/engineering-minimal-change-engineer.md" }),
    Object.freeze({ office: "website-development", department: "performance", slot: 4, name: "Data Visualization & Telemetry Engineer", position: "Performance Telemetry & Data Visualization Engineer", capabilities: Object.freeze(["dashboard-widgets", "metric-visualization", "activity-feed", "time-series-charts"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/ui/**", "media/**"]), writeScope: Object.freeze(["src/ui/**", "media/**"]), commandScope: Object.freeze([]), verification: "Webview telemetry chart renders at 60fps with 10k data points; memory remains bounded.", provenance: "imports/agency-agents/engineering/engineering-data-visualization-engineer.md" }),
    Object.freeze({ office: "app-development", department: "desktop-apps", slot: 1, name: "Desktop Client Architect", position: "Desktop Application & Window Lifecycle Architect", capabilities: Object.freeze(["desktop-architecture", "ipc-messaging", "window-management", "menu-lifecycle"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/**", "package.json"]), writeScope: Object.freeze(["src/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Extension Host / Electron clean activation; process memory boundary tests pass.", provenance: "imports/agency-agents/engineering/engineering-desktop-app-engineer.md" }),
    Object.freeze({ office: "app-development", department: "desktop-apps", slot: 2, name: "Native Interop & OS Integration Specialist", position: "Native OS Bindings & Systems Interop Engineer", capabilities: Object.freeze(["native-addons", "os-bindings", "node-gyp-build", "keychain-access"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node-gyp"]), readScope: Object.freeze(["src/**", "node_modules/**", "binding.gyp"]), writeScope: Object.freeze(["src/**", "binding.gyp"]), commandScope: Object.freeze(["node", "npm"]), verification: "Native module compiles cleanly on Windows x64, macOS arm64, and Linux x64.", provenance: "imports/agency-agents/engineering/engineering-desktop-app-engineer.md" }),
    Object.freeze({ office: "app-development", department: "desktop-apps", slot: 3, name: "Desktop Performance & Resource Optimizer", position: "Desktop Runtime Resource & Memory Specialist", capabilities: Object.freeze(["desktop-memory-tuning", "cold-start-optimization", "process-throttling"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/**", "benchmarks/**"]), writeScope: Object.freeze(["benchmarks/**"]), commandScope: Object.freeze(["node"]), verification: "Cold-start launch <800ms; idle resident memory remains under 120MB threshold.", provenance: "imports/agency-agents/engineering/engineering-autonomous-optimization-architect.md" }),
    Object.freeze({ office: "app-development", department: "desktop-apps", slot: 4, name: "Desktop Packaging & Auto-Update Engineer", position: "Desktop Packaging, Code Signing & Distribution Specialist", capabilities: Object.freeze(["vsix-packaging", "code-signing", "auto-update-setup", "installer-bundle"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:vsce"]), readScope: Object.freeze(["out/**", "package.json", "README.md", "LICENSE"]), writeScope: Object.freeze(["*.vsix", "dist/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Package validation passes with zero vsce warnings; test install and activation succeeds.", provenance: "imports/agency-agents/engineering/engineering-developer-tooling-engineer.md" }),
    Object.freeze({ office: "app-development", department: "mobile-apps", slot: 1, name: "Mobile Application Architect", position: "Cross-Platform Mobile Application Architect", capabilities: Object.freeze(["mobile-architecture", "navigation-stacks", "deep-linking", "lifecycle-state"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "android/**", "ios/**"]), writeScope: Object.freeze(["src/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "App launches and handles background/foreground transitions without state drop.", provenance: "imports/agency-agents/engineering/engineering-mobile-app-builder.md" }),
    Object.freeze({ office: "app-development", department: "mobile-apps", slot: 2, name: "Mobile Touch UI & Gesture Specialist", position: "Mobile Touch Interaction & Animation Specialist", capabilities: Object.freeze(["mobile-gestures", "touch-layout", "haptics-setup", "keyboard-avoidance"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/ui/**", "src/screens/**"]), writeScope: Object.freeze(["src/ui/**", "src/screens/**"]), commandScope: Object.freeze([]), verification: "60fps animation frame rate audit during swipe/gesture drag transitions.", provenance: "imports/agency-agents/design/design-ui-designer.md" }),
    Object.freeze({ office: "app-development", department: "mobile-apps", slot: 3, name: "Mobile Offline Sync & Local Cache Specialist", position: "Mobile Offline Caching & Sync Protocol Engineer", capabilities: Object.freeze(["offline-sync", "local-cache", "mutation-queue", "conflict-resolution"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/storage/**", "src/sync/**"]), writeScope: Object.freeze(["src/storage/**", "src/sync/**"]), commandScope: Object.freeze(["node"]), verification: "Offline mutation queue replay test; zero data loss after simulated network drops.", provenance: "imports/agency-agents/engineering/engineering-database-reliability-engineer.md" }),
    Object.freeze({ office: "app-development", department: "mobile-apps", slot: 4, name: "Mobile Release & Distribution Engineer", position: "Mobile App Store Release & Track Automation Specialist", capabilities: Object.freeze(["mobile-release", "app-signing", "store-metadata", "fastlane-automation"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:fastlane"]), readScope: Object.freeze(["fastlane/**", "android/**", "ios/**"]), writeScope: Object.freeze(["fastlane/**"]), commandScope: Object.freeze(["fastlane", "node"]), verification: "Automated test build and signed bundle generation; store metadata validation pass.", provenance: "imports/agency-agents/engineering/engineering-mobile-release-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-backend-cloud", slot: 1, name: "App Cloud Backend Architect", position: "Cloud Backend & Mobile API Architect", capabilities: Object.freeze(["app-backend", "push-notifications", "client-version-routing"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/backend/**", "src/api/**"]), writeScope: Object.freeze(["src/backend/**", "src/api/**"]), commandScope: Object.freeze(["node"]), verification: "Integration test for multi-version client payload contracts; push payload schema tests.", provenance: "imports/agency-agents/engineering/engineering-backend-architect.md" }),
    Object.freeze({ office: "app-development", department: "app-backend-cloud", slot: 2, name: "App API Gateway & Protocol Engineer", position: "Mobile Protocol & High-Efficiency Gateway Engineer", capabilities: Object.freeze(["payload-optimization", "delta-sync-api", "compression-setup"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/api/**", "schemas/**"]), writeScope: Object.freeze(["src/api/**", "schemas/**"]), commandScope: Object.freeze(["node"]), verification: "Payload benchmark confirms <5KB transfer for core client sync queries.", provenance: "imports/agency-agents/engineering/engineering-api-platform-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-backend-cloud", slot: 3, name: "Identity & Authentication Specialist", position: "Mobile/Desktop Authentication & Session Specialist", capabilities: Object.freeze(["auth-pkce", "token-rotation", "biometric-auth", "session-revocation"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/auth/**"]), writeScope: Object.freeze(["src/auth/**"]), commandScope: Object.freeze(["node"]), verification: "PKCE auth exchange verification; expired token refresh and replay attack rejection tests.", provenance: "imports/agency-agents/engineering/engineering-identity-access-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-backend-cloud", slot: 4, name: "App Privacy & Sandbox Engineer", position: "Application Privacy Controls & Sandbox Compliance Specialist", capabilities: Object.freeze(["privacy-manifest", "pii-scrubbing", "telemetry-optout", "sandbox-compliance"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "PrivacyInfo.xcprivacy"]), writeScope: Object.freeze(["src/**", "PrivacyInfo.xcprivacy"]), commandScope: Object.freeze([]), verification: "Apple Privacy Manifest linting; automated crash report PII leak regex scan passes clean.", provenance: "imports/agency-agents/engineering/engineering-privacy-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-quality-testing", slot: 1, name: "Cross-Platform Test Automation Engineer", position: "Multi-Platform App Test Automation Specialist", capabilities: Object.freeze(["app-e2e-testing", "multi-device-emulation", "smoke-test-flow"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:test-runner"]), readScope: Object.freeze(["tests/**", "src/**"]), writeScope: Object.freeze(["tests/**", "test-results/**"]), commandScope: Object.freeze(["npm", "node"]), verification: "100% smoke test pass across simulated phone, tablet, and desktop viewport sizes.", provenance: "imports/agency-agents/testing/testing-test-automation-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-quality-testing", slot: 2, name: "App Performance & Battery Profiler", position: "App Battery & Energy Consumption Profiler", capabilities: Object.freeze(["battery-profiling", "wake-lock-audit", "energy-optimization"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "benchmarks/**"]), writeScope: Object.freeze(["benchmarks/**"]), commandScope: Object.freeze([]), verification: "Zero unnecessary background wake locks; energy impact rating verified at 'Low'.", provenance: "imports/agency-agents/testing/testing-performance-benchmarker.md" }),
    Object.freeze({ office: "app-development", department: "app-quality-testing", slot: 3, name: "App Store Compliance & DX Specialist", position: "Store Policy Compliance & Developer Experience Specialist", capabilities: Object.freeze(["store-compliance-audit", "permission-justification", "dx-review"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/compliance/**", "package.json", "manifest.json"]), writeScope: Object.freeze(["docs/compliance/**"]), commandScope: Object.freeze([]), verification: "Compliance scorecard confirms 100% compliance with current store review rules.", provenance: "imports/agency-agents/product/product-dx-engineer.md" }),
    Object.freeze({ office: "app-development", department: "app-quality-testing", slot: 4, name: "Crash Analytics & Diagnostics Specialist", position: "Crash Clustering & Runtime Diagnostics Specialist", capabilities: Object.freeze(["crash-triage", "symbolication", "anr-investigation", "crash-regression-test"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/**", "tests/**", "crash-reports/**"]), writeScope: Object.freeze(["tests/**"]), commandScope: Object.freeze(["node"]), verification: "Every resolved crash has a reproducible automated regression test case that passes.", provenance: "imports/agency-agents/testing/testing-test-results-analyzer.md" }),
    Object.freeze({ office: "research-making", department: "research-synthesis", slot: 1, name: "Technical Research Synthesist", position: "Lead Technical Research & Literature Synthesist", capabilities: Object.freeze(["research-synthesis", "tradeoff-analysis", "library-evaluation", "technical-brief"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/research/**", "README.md"]), writeScope: Object.freeze(["docs/research/**"]), commandScope: Object.freeze([]), verification: "Evidence-backed research report with citation links and comparative trade-off tables.", provenance: "imports/agency-agents/research/research-synthesist.md" }),
    Object.freeze({ office: "research-making", department: "research-synthesis", slot: 2, name: "Codebase Archaeologist & Reverse Engineer", position: "Legacy Code Archaeology & Reverse Engineering Specialist", capabilities: Object.freeze(["codebase-archaeology", "legacy-extraction", "reverse-engineering", "call-graph-mapping"]), toolRequirements: Object.freeze(["filesystem:read", "process:execute:git"]), readScope: Object.freeze(["src/**", "legacy/**", "package.json"]), writeScope: Object.freeze(["docs/architecture/**"]), commandScope: Object.freeze(["git", "node"]), verification: "Accurate architecture map and dependency graph verified against current codebase symbols.", provenance: "imports/agency-agents/specialized/specialized-codebase-archaeologist.md" }),
    Object.freeze({ office: "research-making", department: "research-synthesis", slot: 3, name: "Technology Trend & Feasibility Analyst", position: "Technology Feasibility & Evaluation Analyst", capabilities: Object.freeze(["feasibility-spike", "technology-evaluation", "risk-assessment"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/research/**", "package.json"]), writeScope: Object.freeze(["docs/research/**"]), commandScope: Object.freeze([]), verification: "Feasibility spike report with risk matrix and concrete go/no-go recommendation criteria.", provenance: "imports/agency-agents/product/product-trend-researcher.md" }),
    Object.freeze({ office: "research-making", department: "research-synthesis", slot: 4, name: "Knowledge Graph & Memory Architect", position: "Organizational Knowledge Graph & Semantic Memory Architect", capabilities: Object.freeze(["knowledge-graph", "memory-modeling", "entity-extraction", "decision-indexing"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/domain/memory*.js", "docs/memory/**"]), writeScope: Object.freeze(["src/domain/memory*.js", "docs/memory/**"]), commandScope: Object.freeze([]), verification: "Knowledge schema validation; recall query test returns relevant historical decisions accurately.", provenance: "imports/agency-agents/engineering/engineering-knowledge-graph-engineer.md" }),
    Object.freeze({ office: "research-making", department: "prototyping-experimental", slot: 1, name: "Rapid Software Prototyper", position: "Fast Proof-of-Concept & Interactive Spike Prototyper", capabilities: Object.freeze(["rapid-poc", "experimental-spike", "feasibility-demo"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["src/**", "scratch/**"]), writeScope: Object.freeze(["scratch/**", "experiments/**"]), commandScope: Object.freeze(["node", "npm"]), verification: "Working executable prototype demonstration with verified functional smoke test.", provenance: "imports/agency-agents/engineering/engineering-rapid-prototyper.md" }),
    Object.freeze({ office: "research-making", department: "prototyping-experimental", slot: 2, name: "Embedded Systems & Firmware Engineer", position: "Embedded Microcontroller & Hardware Firmware Specialist", capabilities: Object.freeze(["firmware-development", "sensor-driver", "rtos-tasks", "hardware-communication"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:gcc-arm"]), readScope: Object.freeze(["firmware/**", "hardware/**"]), writeScope: Object.freeze(["firmware/**"]), commandScope: Object.freeze(["make", "gcc", "clang"]), verification: "Firmware builds without warnings; static memory allocation analysis shows stack/heap within bounds.", provenance: "imports/agency-agents/engineering/engineering-embedded-firmware-engineer.md" }),
    Object.freeze({ office: "research-making", department: "prototyping-experimental", slot: 3, name: "IoT & Connected Devices Specialist", position: "IoT Device Fleet & Telemetry Protocol Specialist", capabilities: Object.freeze(["iot-telemetry", "ota-update", "mqtt-broker", "device-provisioning"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["iot/**", "config/iot/**"]), writeScope: Object.freeze(["iot/**"]), commandScope: Object.freeze(["node"]), verification: "MQTT packet delivery verified under simulated 20% packet loss network condition.", provenance: "imports/agency-agents/engineering/engineering-iot-fleet-engineer.md" }),
    Object.freeze({ office: "research-making", department: "prototyping-experimental", slot: 4, name: "Systems Refactoring & Safety Specialist", position: "Low-Level Systems Refactoring & Memory Safety Specialist", capabilities: Object.freeze(["systems-refactoring", "memory-safety-audit", "rust-integration", "ffi-bindings"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:cargo"]), readScope: Object.freeze(["native/**", "src/**"]), writeScope: Object.freeze(["native/**"]), commandScope: Object.freeze(["cargo", "rustc"]), verification: "cargo test passes; cargo clippy and miri verify zero undefined behavior / memory leaks.", provenance: "imports/agency-agents/engineering/engineering-rust-refactoring-specialist.md" }),
    Object.freeze({ office: "research-making", department: "ai-systems-evaluation", slot: 1, name: "AI Agent Prompt & Persona Engineer", position: "Prompt Architecture & Structured Contract Specialist", capabilities: Object.freeze(["prompt-design", "structured-output", "few-shot-tuning", "persona-calibration"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/application/promptRegistry.js", "prompts/**"]), writeScope: Object.freeze(["src/application/promptRegistry.js", "prompts/**"]), commandScope: Object.freeze([]), verification: "Structured output validation passes 100/100 test runs; prompt token budget stays within limits.", provenance: "imports/agency-agents/engineering/engineering-prompt-engineer.md" }),
    Object.freeze({ office: "research-making", department: "ai-systems-evaluation", slot: 2, name: "Model Quality & Hallucination Evaluator", position: "AI Model Evaluation & Quality Benchmark Specialist", capabilities: Object.freeze(["model-eval", "hallucination-scoring", "accuracy-benchmarking", "drift-monitoring"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["evals/**", "tests/**"]), writeScope: Object.freeze(["evals/**"]), commandScope: Object.freeze(["node"]), verification: "Automated eval scorecard verifies model output quality meets >95% accuracy rubric.", provenance: "imports/agency-agents/specialized/specialized-model-qa.md" }),
    Object.freeze({ office: "research-making", department: "ai-systems-evaluation", slot: 3, name: "RAG & Retrieval Systems Specialist", position: "Retrieval-Augmented Generation & Vector Chunking Specialist", capabilities: Object.freeze(["rag-tuning", "chunking-strategy", "retrieval-ranking", "context-packing"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/domain/memory*.js", "src/application/context*.js"]), writeScope: Object.freeze(["src/domain/memory*.js", "src/application/context*.js"]), commandScope: Object.freeze(["node"]), verification: "RAG benchmark verifies Mean Reciprocal Rank (MRR@5) > 0.85; zero context window overflows.", provenance: "imports/agency-agents/engineering/engineering-rag-pipeline-engineer.md" }),
    Object.freeze({ office: "research-making", department: "ai-systems-evaluation", slot: 4, name: "Automation Governance & Ethics Architect", position: "AI Governance, Safety Boundaries & Human-in-the-Loop Architect", capabilities: Object.freeze(["governance-policy", "safety-guardrails", "human-approval-gate", "audit-enforcement"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["src/domain/invariants.js", "src/domain/planApproval.js"]), writeScope: Object.freeze(["src/domain/invariants.js", "src/domain/planApproval.js"]), commandScope: Object.freeze([]), verification: "Adversarial simulation verifies prohibited tools and unapproved plans are blocked 100% of the time.", provenance: "imports/agency-agents/specialized/automation-governance-architect.md" }),
    Object.freeze({ office: "research-making", department: "documentation-publishing", slot: 1, name: "Lead Technical Writer", position: "Senior Technical Writer & Architecture Documentation Specialist", capabilities: Object.freeze(["adr-authoring", "api-documentation", "architecture-guides", "release-notes"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/**", "README.md", "RELEASE_POLICY.md"]), writeScope: Object.freeze(["docs/**", "README.md", "RELEASE_POLICY.md"]), commandScope: Object.freeze([]), verification: "Documentation linter passes; all file links and code block syntax verified valid.", provenance: "imports/agency-agents/engineering/engineering-technical-writer.md" }),
    Object.freeze({ office: "research-making", department: "documentation-publishing", slot: 2, name: "Developer Documentation & DX Specialist", position: "Developer Experience & Tutorial Authoring Specialist", capabilities: Object.freeze(["quickstart-authoring", "developer-guides", "code-samples", "faq-curation"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["docs/dev/**", "examples/**"]), writeScope: Object.freeze(["docs/dev/**", "examples/**"]), commandScope: Object.freeze([]), verification: "New developer walkthrough test: code sample executes cleanly with zero missing prerequisite errors.", provenance: "imports/agency-agents/product/product-dx-engineer.md" }),
    Object.freeze({ office: "research-making", department: "documentation-publishing", slot: 3, name: "Document Compiler & Publishing Engineer", position: "Multi-Format Documentation Pipeline Specialist", capabilities: Object.freeze(["doc-compilation", "dead-link-check", "static-site-build", "pdf-export"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write", "process:execute:node"]), readScope: Object.freeze(["docs/**", "scripts/**"]), writeScope: Object.freeze(["docs/build/**"]), commandScope: Object.freeze(["node"]), verification: "Documentation build generates 100% clean output; dead link checker reports 0 broken links.", provenance: "imports/agency-agents/engineering/engineering-universal-document-compiler.md" }),
    Object.freeze({ office: "research-making", department: "documentation-publishing", slot: 4, name: "Experimental Spike & Results Steward", position: "Experiment Hypothesis & Evidence Logging Steward", capabilities: Object.freeze(["hypothesis-logging", "experiment-archiving", "durable-handoff", "result-stewarding"]), toolRequirements: Object.freeze(["filesystem:read", "filesystem:write"]), readScope: Object.freeze(["experiments/**", "docs/experiments/**"]), writeScope: Object.freeze(["docs/experiments/**"]), commandScope: Object.freeze([]), verification: "Hypothesis-evidence pair recorded for every spike; results verified by independent test data.", provenance: "imports/agency-agents/project-management/project-management-experiment-tracker.md" }),
];

function invalidScope(scope) {
    try {
        assertScopePattern(scope);
        return false;
    } catch {
        return true;
    }
}

const OFFICE_SLUGS = new Set(OFFICE_CATALOG.map((office) => office.slug));
const TOOL_PATTERN = /^(filesystem:(read|write)|process:execute:[a-z0-9]+(-[a-z0-9]+)*)$/;

function validateCatalog() {
    const errors = [];
    const byDepartment = new Map();
    const positionNames = new Set();
    if (POSITION_DEFS.length !== 80) errors.push('catalog must hold exactly 80 positions');
    for (const entry of POSITION_DEFS) {
        const key = entry.office + '/' + entry.department;
        const group = byDepartment.get(key) || [];
        group.push(entry);
        byDepartment.set(key, group);
        if (!OFFICE_SLUGS.has(entry.office)) errors.push('unknown office: ' + entry.office);
        if (!Number.isInteger(entry.slot) || entry.slot < 1 || entry.slot > 4) errors.push('bad slot: ' + key);
        if (typeof entry.name !== 'string' || !entry.name.trim() || entry.name.length > 100) errors.push('bad name: ' + key);
        const normalizedName = typeof entry.name === 'string' ? entry.name.trim().toLocaleLowerCase('en-US') : '';
        if (normalizedName && positionNames.has(normalizedName)) errors.push('position specialization names must be globally unique: ' + entry.name);
        positionNames.add(normalizedName);
        if (typeof entry.position !== 'string' || !entry.position.trim()) errors.push('bad position title: ' + key);
        if (!Array.isArray(entry.capabilities) || entry.capabilities.length === 0
            || entry.capabilities.some((label) => typeof label !== 'string' || !/^[a-z0-9]+(-[a-z0-9]+)*$/.test(label) || label.length > 100)) {
            errors.push('bad capabilities: ' + key + ' slot ' + entry.slot);
        }
        if (!Array.isArray(entry.toolRequirements) || entry.toolRequirements.length === 0
            || entry.toolRequirements.some((tool) => typeof tool !== 'string' || !TOOL_PATTERN.test(tool))) {
            errors.push('bad toolRequirements: ' + key + ' slot ' + entry.slot);
        }
        for (const scopeField of ['readScope', 'writeScope', 'commandScope']) {
            const scopes = entry[scopeField];
            if (!Array.isArray(scopes) || scopes.length > 20
                || scopes.some((scope) => typeof scope !== 'string' || invalidScope(scope))) {
                errors.push('bad ' + scopeField + ': ' + key + ' slot ' + entry.slot);
            }
        }
        if (typeof entry.verification !== 'string' || !entry.verification.trim() || entry.verification.length > 300) errors.push('bad verification: ' + key);
        if (typeof entry.provenance !== 'string' || !entry.provenance.startsWith('imports/agency-agents/')) errors.push('bad provenance: ' + key);
    }
    for (const [key, group] of byDepartment) {
        if (group.length !== 4) errors.push(key + ' must hold exactly four positions');
        if (new Set(group.map((entry) => entry.slot)).size !== 4) errors.push(key + ' slots must be 1-4');
        if (new Set(group.map((entry) => entry.name.trim().toLowerCase())).size !== 4) errors.push(key + ' specializations must be distinct');
    }
    if (errors.length) throw new DomainInvariantError('invalid-position-catalog', 'Position catalog invariants failed: ' + errors.join('; '));
    return byDepartment;
}

const CATALOG_BY_DEPARTMENT = validateCatalog();

/** All eighty native positions, frozen, ordered by office then department. */
export const POSITION_CATALOG = Object.freeze(POSITION_DEFS.map((entry) => Object.freeze({ ...entry,
    capabilities: Object.freeze([...entry.capabilities]),
    toolRequirements: Object.freeze([...entry.toolRequirements]),
    readScope: Object.freeze([...entry.readScope]),
    writeScope: Object.freeze([...entry.writeScope]),
    commandScope: Object.freeze([...entry.commandScope]) })));

/** Department slugs defined for one office, in catalog order. */
export function getPositionDepartments(officeSlug) {
    const slugs = [];
    for (const [key] of CATALOG_BY_DEPARTMENT) {
        if (key.startsWith(officeSlug + '/')) slugs.push(key.slice(officeSlug.length + 1));
    }
    return Object.freeze(slugs);
}

/** The four canonical positions for one department; throws on unknown office/department. */
export function getDepartmentPositions(officeSlug, departmentSlug) {
    const group = CATALOG_BY_DEPARTMENT.get(officeSlug + '/' + departmentSlug);
    if (!group) throw new DomainInvariantError('unknown-department-position', 'No catalog positions for ' + officeSlug + '/' + departmentSlug);
    return Object.freeze(group.map((entry) => Object.freeze({ ...entry,
        capabilities: Object.freeze([...entry.capabilities]),
        toolRequirements: Object.freeze([...entry.toolRequirements]),
        readScope: Object.freeze([...entry.readScope]),
        writeScope: Object.freeze([...entry.writeScope]),
        commandScope: Object.freeze([...entry.commandScope]) })));
}

/** Positions whose declared capabilities include the given label (case-insensitive). */
export function findPositionsByCapability(label) {
    if (typeof label !== 'string' || !label.trim()) return [];
    const needle = label.trim().toLocaleLowerCase('en-US');
    return POSITION_CATALOG.filter((entry) => entry.capabilities.some((capability) => capability.toLocaleLowerCase('en-US') === needle));
}

/** Resolve a persisted employee specialization to its unique catalog position.
 * Unmapped legacy/custom specializations return null and retain their existing
 * explicitly granted task scope. */
export function findPositionBySpecialization(specialization) {
    if (typeof specialization !== 'string' || !specialization.trim()) return null;
    const needle = specialization.trim().toLocaleLowerCase('en-US');
    return POSITION_CATALOG.find((entry) => entry.name.toLocaleLowerCase('en-US') === needle) ?? null;
}
