import type { AgentRole, ObjectiveStatus, TaskStatus } from '../../constants';
import type { EntityId } from '../../shared/identifiers';

/** Persisted repository records include timestamps generated by SQLite. */
export interface TimestampedRecord {
  readonly id: EntityId;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface OrganizationRecord extends TimestampedRecord {
  readonly name: string;
}

export interface ObjectiveRecord extends TimestampedRecord {
  readonly title: string;
  readonly description: string;
  readonly status: ObjectiveStatus;
  readonly priority: number;
}

export type ProjectStatus = 'PLANNING' | 'ACTIVE' | 'COMPLETED' | 'FAILED' | 'PAUSED';
export interface ProjectRecord extends TimestampedRecord {
  readonly name: string;
  readonly description: string | null;
  readonly status: ProjectStatus;
  readonly priority: number;
  readonly objectiveId: EntityId | null;
}

export type AgentStatus = 'IDLE' | 'BUSY' | 'OFFLINE' | 'ERROR';
export interface AgentRecord extends TimestampedRecord {
  readonly name: string;
  readonly role: AgentRole;
  readonly specialization: string | null;
  readonly status: AgentStatus;
  readonly managedOfficeId: EntityId | null;
  readonly managedDepartmentId: EntityId | null;
  readonly departmentId: EntityId | null;
}

export interface TaskRecord extends TimestampedRecord {
  readonly taskCode: string;
  readonly title: string;
  readonly description: string | null;
  readonly status: TaskStatus;
  readonly priority: number;
  readonly projectId: EntityId | null;
  readonly assigneeId: EntityId | null;
  readonly creatorId: EntityId | null;
  readonly acceptanceCriteria: string | null;
  readonly result: string | null;
  readonly blockerReason: string | null;
  readonly retryCount: number;
  readonly maxRetries: number;
  readonly tokenBudget: number | null;
  readonly timeBudgetMs: number | null;
  readonly startedAt: string | null;
  readonly completedAt: string | null;
}

export type DirectorQuestionStatus = 'PENDING' | 'ANSWERED' | 'SKIPPED';
export interface DirectorQuestionRecord extends TimestampedRecord {
  readonly objectiveId: EntityId;
  readonly question: string;
  readonly answer: string | null;
  readonly status: DirectorQuestionStatus;
  readonly category: string | null;
  readonly sortOrder: number;
}

export interface NewOrganization {
  readonly id: EntityId;
  readonly name: string;
}
export type OrganizationChanges = Partial<Omit<NewOrganization, 'id'>>;

export interface NewObjective {
  readonly id: EntityId;
  readonly title: string;
  readonly description: string;
  readonly status?: ObjectiveStatus;
  readonly priority?: number;
}
export type ObjectiveChanges = Partial<Omit<NewObjective, 'id'>>;

export interface NewProject {
  readonly id: EntityId;
  readonly name: string;
  readonly description?: string | null;
  readonly status?: ProjectStatus;
  readonly priority?: number;
  readonly objectiveId?: EntityId | null;
}
export type ProjectChanges = Partial<Omit<NewProject, 'id'>>;

export interface NewAgent {
  readonly id: EntityId;
  readonly name: string;
  readonly role: AgentRole;
  readonly specialization?: string | null;
  readonly status?: AgentStatus;
  readonly managedOfficeId?: EntityId | null;
  readonly managedDepartmentId?: EntityId | null;
  readonly departmentId?: EntityId | null;
}
export type AgentChanges = Partial<Omit<NewAgent, 'id'>>;

export interface NewTask {
  readonly id: EntityId;
  readonly taskCode: string;
  readonly title: string;
  readonly description?: string | null;
  readonly status?: TaskStatus;
  readonly priority?: number;
  readonly projectId?: EntityId | null;
  readonly assigneeId?: EntityId | null;
  readonly creatorId?: EntityId | null;
  readonly acceptanceCriteria?: string | null;
  readonly result?: string | null;
  readonly blockerReason?: string | null;
  readonly retryCount?: number;
  readonly maxRetries?: number;
  readonly tokenBudget?: number | null;
  readonly timeBudgetMs?: number | null;
  readonly startedAt?: string | null;
  readonly completedAt?: string | null;
}
export type TaskChanges = Partial<Omit<NewTask, 'id'>>;

export interface NewDirectorQuestion {
  readonly id: EntityId;
  readonly objectiveId: EntityId;
  readonly question: string;
  readonly answer?: string | null;
  readonly status?: DirectorQuestionStatus;
  readonly category?: string | null;
  readonly sortOrder?: number;
}
export type DirectorQuestionChanges = Partial<Omit<NewDirectorQuestion, 'id'>>;
